config/routes.rb
Rails.application.routes.draw do

  get 'user_role/edit'

  get 'user_role/json'

  get 'summit/create'

  get 'summit/new'

  get 'dashboard/index'

  post 'user_role/change_role', to: "user_role#change_role"

  get 'user_role/edit'

  get 'user_role/json', to: 'user_role#json'

  post 'summit/new', :to => "summit#create"

  get 'email/:id/choose', :to => "email#choose", as: 'email_choose'

  post 'email/:id/preview', :to => "email#preview", as: 'email_preview'

  post 'email/:id/send', :to => "email#send_email", as: 'email_send'

  get 'interview/:id/signup', :to => "interview#signup", as: 'interview_signup'

  get 'interview/:id/cancel', :to => "interview#cancel", as: 'interview_cancel'

  get 'interview/index'

  get 'interview/show'

  get 'interview/update'

  get 'interview/admin'

  get 'written_rating/edit'

  get 'written_rating/update'

  get 'written_rating/new'

  get 'question/review' => 'question#review'

  get '/application_submission_data/:form_id', to: 'application_submission#view_submissions'

  resources :application_submission, :question, :written_rating, :interview, :email, :application_form
  devise_for :users, :controllers => { registrations: 'registrations' }
  get "/application_create/:form_id/:user_id" => "application_submission#new_submission"
  get "/new_app_submission/:form_id" => "application_submission#new_user"
  get "/new_user" => "application_submission#new_admin"         #admin

  get 'application/index'

  get 'application/new'

  get 'application/edit'

  get 'welcome/index'

  

  root 'welcome#index'

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
  	redirect_to "/new_app_submission/1" if !current_user
  	@owned_forms = current_user.application_forms
  end

end

app/views/dashboard/index.html.erb
<h1>Dashboard</h1>
<% if current_user.is_admin? %>
<!-- <%= link_to "Change/Add/Remove Interview Timeslots", interview_admin_path %><BR> -->
<%= link_to "Create New Form", "/application_form/new" %><BR>
<%= link_to "Manage User Roles", "/user_role/edit" %><BR>
<% if user_signed_in? %>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
<% end %>

<% end %>
<!-- <% if !current_user.is_applicant? %> -->
<!-- <%= link_to "Sign Up for Interviews", interview_index_path %><BR> -->
<!-- <% end %> -->
<% if current_user.is_applicant? %>
	<%= link_to "View My Application", edit_application_submission_path(current_user.application_submission.id) %><BR>
<% end %>
<% if current_user.is_admin? && @owned_forms %>
	<h4>Your Forms:</h4>
	<li>
	<% @owned_forms.each do |o| %>
		<%= link_to o.title, application_form_path(o) %>
	<% end %>
	</li><BR>
<% end %>