config/routes.rb
Rails.application.routes.draw do

  get 'user_role/edit'

  get 'user_role/json'

  get 'summit/create'

  get 'summit/new'

  get 'dashboard/index'

  post 'user_role/change_role', to: "user_role#change_role"

  get 'user_role/edit'

  get 'user_role/json', to: 'user_role#json'

  post 'summit/new', :to => "summit#create"

  get 'email/:id/choose', :to => "email#choose", as: 'email_choose'

  post 'email/:id/preview', :to => "email#preview", as: 'email_preview'

  post 'email/:id/send', :to => "email#send_email", as: 'email_send'

  get 'interview/:id/signup', :to => "interview#signup", as: 'interview_signup'

  get 'interview/:id/cancel', :to => "interview#cancel", as: 'interview_cancel'

  get 'interview/index'

  get 'interview/show'

  get 'interview/update'

  get 'interview/admin'

  get 'written_rating/edit'

  get 'written_rating/update'

  get 'written_rating/new'

  get 'question/review' => 'question#review'

  get '/application_submission_data/:form_id', to: 'application_submission#view_submissions'

  resources :application_submission, :question, :written_rating, :interview, :email, :application_form
  devise_for :users, :controllers => { registrations: 'registrations' }
  get "/application_create/:form_id/:user_id" => "application_submission#new_submission"
  get "/new_app_submission/:form_id" => "application_submission#new_user"
  get "/new_user" => "application_submission#new_admin"         #admin

  get 'application/index'

  get 'application/new'

  get 'application/edit'

  get 'welcome/index'

  

  root 'welcome#index'

end

app/models/application_submission.rb
class ApplicationSubmission < ActiveRecord::Base
  belongs_to :user
  belongs_to :application_form
  has_many :written_ratings
  has_many :answers

  # the order of this enum is important
  # because :unreviewed is mapped to 0 and
  # 0 is stored in the DB.
  enum round: [
    :unreviewed,
    :written_app_reject,
    :written_app_accept,
    :first_interview_reject,
    :first_interview_accept,
    :second_interview_reject,
    :second_interview_accept,
  ]

  def applicant_name
    return user.name
  end

  def has_been_rated_by(user)
    rating = written_ratings.find_by_user_id(user)
    return false if rating == nil
    return false if rating[:rating] == nil
    return true
  end

  def avg_written_rating
    sum_rating = written_ratings.inject(0) do |sum, x| 
      sum = x[:rating].to_i + sum if x 
    end
    if written_ratings.empty?
      return 0
    else
      return sum_rating / written_ratings.size
    end
  end

  def rating_for(user)
    return written_ratings.find_by_user_id(user.id)
  end

  def matching_qs
  	return Question.where(application_form_id: self.application_form_id)
  end

  def init_answers
  	#go through and create answers for every existing question in app form
  	all_questions = matching_qs
  	all_questions.each do |q|
  		answers.create(question_id:q.id, text: "") if !self.answers.pluck(:question_id).include?(q.id)
  	end
  end

  def grab_qas
    init_answers if answers.size != application_form.questions.size
    data = self.answers.map{|a| {a.question => a}} 
    return data
  end
  
end

app/controllers/application_submission_controller.rb
class ApplicationSubmissionController < ApplicationController

  def index
    redirect_to welcome_index_path
    #redirect_to welcome_index_path if current_user.is_applicant?
    #@apps = ApplicationSubmission.all
  end

  def view_submissions
    redirect_to welcome_index_path if current_user.is_applicant?
    @app_form = ApplicationForm.find(params[:form_id])
    @apps = @app_form.application_submissions
    @rounds = ApplicationSubmission.rounds
  end

  def new_user 
    redirect_to new_user_registration_path+"?form_id="+params[:form_id]
  end

  def new_admin
    redirect_to new_user_registration_path+"?is_admin=2"
  end

  def new_submission #/application_create/(:form_id)/(:user_id)
    if !current_user
      cur_user = User.find(params[:user_id])
      cur = cur_user.init_application_with_id(params[:form_id])
      redirect_to edit_application_submission_url(cur.id)
      return
    end
    cur = current_user.application_submission
    if cur == nil
      cur = current_user.init_application_with_id(params[:form_id])
    end
	  redirect_to edit_application_submission_url(cur.id)
  end

  def edit
  	@application_submission = ApplicationSubmission.find(params[:id])
  	@questions_and_answers = @application_submission.grab_qas
  end

  def create
  end

  def update
    if params[:round] #change round
      round_num = round_params.keys[0].to_i
      app = ApplicationSubmission.find(params[:id])
      app.update(round: round_num)
      # user_email = app.user.email
      # if round_num == 0
      #   Postman.reject_email(user_email).deliver
      # elsif round_num == 2
      #   Postman.first_round_email(user_email).deliver
      # end
    else
      answers = answer_set_params
      answers.each do |id, text|
        Answer.find(id).update(text: text)
      end
    end
    if params[:commit] == "Submit"
      ApplicationSubmission.update(params[:id], :submitted => true)
    end
    redirect_to :back
  end

  def destroy
  end

  def show

    @application_submission = ApplicationSubmission.find(params[:id])
    @questions_and_answers = @application_submission.grab_qas
    @user_rating = @application_submission.rating_for(current_user)
    if @user_rating == nil
      @user_rating = @application_submission.written_ratings.create(user_id: current_user.id)
    end
    @user = @application_submission.user
    @all_ratings = @application_submission.written_ratings.where.not(comment: nil)
  end

  private

    def answer_set_params
      params.require(:answers)
    end
    def round_params
      params.require(:round)
    end
end

app/helpers/application_submission_helper.rb
module ApplicationSubmissionHelper
end

app/views/application_submission/create.html.erb
<h4>Submitted!</h4>
<i>We look forward to reading your application!</i>

app/views/application_submission/destroy.html.erb
<h1>ApplicationSubmission#destroy</h1>
<p>Find me in app/views/application_submission/destroy.html.erb</p>

app/views/application_submission/edit.html.erb
<% if @application_submission.submitted %>
	<% @questions_and_answers.each do |q| %>
		<%  question = q.keys[0] 
			answer = q.values[0]
		%>
		<div class="question">
			<%= question.text %>
			<div class="answer">
				<%= answer.text %>
			</div>
		</div>
	<% end %>
	<div class="note">Your application has been submitted.</div>
<% else %>
	<%= form_for @application_submission, url: {action: "update"} do |f| %>
		<% @questions_and_answers.each do |q| %>
			<%  question = q.keys[0] 
				answer = q.values[0] %>
			<div class="question">
				<%= question.text %>
				<div class="answer">
					<%= text_field_tag "answers[" + answer.id.to_s + "]", answer.text %>
				</div>
			</div>
		<% end %>
		<div class="note">Save frequently. Submissions are final.</div>
		<%= f.submit "Save" %>
		<%= f.submit "Submit" %>
	<% end %>
<% end %>

app/views/application_submission/index.html.erb
<table>
	<tr>
		<td>Rated?</td>
		<td>Application Name</td>
		<td>Written Avg Score</td>
		<td>Interview</td>
		<% if current_user.is_admin? %>
		<td>Status</td>
		<td>Action</td>
		<% end %>
	</tr>
	<% @apps.each do |app| %>
		<% interview = Interview.find_by_applicant_id(app.user.id) %>
		<tr>
			<td><%= bool_to_string(app.has_been_rated_by(current_user.id)) %></td>
			<td><%= link_to app.applicant_name, app %></td>
			<td><%= app.avg_written_rating %></td>
			<td>
				<% if interview == nil %>
					n/a
				<% else %>
					<%= link_to "link", interview_path(interview.id) %>
				<% end %>
			</td>
			<td>
				<% if current_user.is_admin? %>
					<% if app.round == 1 %> <!-- not modified -->
						-
					<% elsif app.round == 0 %> <!-- rejected -->
						Rejected
					<% else %>	<!-- moved on -->
						OK				
					<% end %>
				<% end %>
			</td>
			<td>
				<% if current_user.is_admin? %>
					<%= form_for app, url: application_submission_path(app), method: :patch do |f| %>
						<%= f.submit "move on", name:'round[2]', data:{ confirm:'Are you would like to move this applicant on?'} %>
						<%= f.submit "reject", name:'round[0]', data:{confirm:'Are you would like to reject this applicant?'} %>
					<% end %>
				<% end %>
			</td>
		</tr>
	<% end %>
</table>

app/views/application_submission/show.html.erb
<%= link_to "Back to All Submissions", :back %>
<BR>
	<%= link_to image_tag(@user.image.url(:med)), @user.image.url %>
	<h4>Applicant Name: <%= @user.name %></h4>
	<%= @user.name %>'s Email: <a href="mailto:<%= @user.email %>"><%= @user.email %></a><BR>
	<%= @user.name %>'s Resume: <%= link_to "Link", @user.resume.url %><BR>
	<%= @user.name %>'s Face: <%= link_to "Link", @user.image.url %>
<div class="status">Status:
<% if @application_submission.submitted %>
	Submitted
<% else %>
	Not submitted
<% end %>
</div>
<BR>
<% @questions_and_answers.each do |qa| %>
	<% question = qa.keys[0] 
		answer = qa.values[0]
	%>
	<div class="qa_grouping">
		<span class="question"><b><%= question.text %></b></span><BR>
		<span class="answer"><%= answer.text %></span> 
	</div>
<% end %>

<div id="app_rating">
	<h2>Rate</h2>
	<%= form_for @user_rating, url: {action: "update", controller: "written_rating", id: @user_rating.id} do |f| %>
		<%= f.text_area :comment %>
		<%= select_tag("written_rating[rating]", options_for_select([["1",1],["2",2],["3",3]])) %>
		<%= f.submit %>
	<% end %>
</div>

<div id="all_ratings">
	<h3>All Ratings:</h3>
	<% if @all_ratings.size == 0 %>
	<i>No ratings found!</i>
	<% end %>
	<% @all_ratings.each do |r| %>
	<div class="rating_block">
		<b><%= r.user.name %></b>
		<i><%= r.rating %></i><BR>
		<b>Comments:</b><BR>
		<span class="comment"><%= r.comment %></span>	
	</div>
		
	<% end %>
</div>

app/views/application_submission/view_submissions.html.erb
<h2>All Submissions for <%= @app_form.title %></h2>
<table>
	<tr>
		<td>Rated?</td>
		<td>Application Name</td>
		<td>Submitted Date</td>
		<td>Written Avg Score</td>
		<td>Interview</td>
		<% if current_user.is_admin? %>
		<td>Status</td>
		<td>Action</td>
		<% end %>
	</tr>
	<% @apps.each do |app| %>
		<% interview = Interview.find_by_applicant_id(app.user.id) %>
		<tr>
			<td><%= bool_to_string(app.has_been_rated_by(current_user.id)) %></td>
			<td><%= link_to app.applicant_name, app %></td>
			<td><%= app.created_at.strftime("%b %d") %></td>
			<td><%= app.avg_written_rating %></td>
			<td>
				<% if interview == nil %>
					n/a
				<% else %>
					<%= link_to "link", interview_path(interview.id) %>
				<% end %>
			</td>
			<td>
				<% if current_user.is_admin? %>
					<%= app.round.humanize %>
				<% end %>
			</td>
			<td>
				<% if current_user.is_admin? %>
					<%= form_for app, url: application_submission_path(app), method: :patch do |f| %>
						<% @rounds.each do |name, i| %>
							<%= f.submit name.humanize, name:'round[' + i.to_s + ']', data:{confirm:'Fosho?'} %>
						<% end %>
					<% end %>
				<% end %>
			</td>
		</tr>
	<% end %>
</table>