config/routes.rb
Rails.application.routes.draw do

  get 'user_role/edit'

  get 'user_role/json'

  get 'summit/create'

  get 'summit/new'

  get 'dashboard/index'

  post 'user_role/change_role', to: "user_role#change_role"

  get 'user_role/edit'

  get 'user_role/json', to: 'user_role#json'

  post 'summit/new', :to => "summit#create"

  get 'email/:id/choose', :to => "email#choose", as: 'email_choose'

  post 'email/:id/preview', :to => "email#preview", as: 'email_preview'

  post 'email/:id/send', :to => "email#send_email", as: 'email_send'

  get 'interview/:id/signup', :to => "interview#signup", as: 'interview_signup'

  get 'interview/:id/cancel', :to => "interview#cancel", as: 'interview_cancel'

  get 'interview/index'

  get 'interview/show'

  get 'interview/update'

  get 'interview/admin'

  get 'written_rating/edit'

  get 'written_rating/update'

  get 'written_rating/new'

  get 'question/review' => 'question#review'

  get '/application_submission_data/:form_id', to: 'application_submission#view_submissions'

  resources :application_submission, :question, :written_rating, :interview, :email, :application_form
  devise_for :users, :controllers => { registrations: 'registrations' }
  get "/application_create/:form_id/:user_id" => "application_submission#new_submission"
  get "/new_app_submission/:form_id" => "application_submission#new_user"
  get "/new_user" => "application_submission#new_admin"         #admin

  get 'application/index'

  get 'application/new'

  get 'application/edit'

  get 'welcome/index'

  

  root 'welcome#index'

end

app/controllers/interview_controller.rb
class InterviewController < ApplicationController
  before_action :authenticate_user!
  def index
    @new_interview = Interview.new
    if current_user.is_admin? or current_user.is_reviewer?
      @interviews = @new_interview.get_nil_interviewer
      @my_interviews = @new_interview.belong_to_interviewer(current_user.id)
    else
      @interviews = @new_interview.get_available_interviews
      @my_interviews = @new_interview.belong_to_applicant(current_user.id)
    end
  end

  def show
  end

  def update
    i = Interview.find(params[:id])
    i.update!(interview_update_params)
    redirect_to :back
  end

  def create
  	event = interview_params
  	interview_time = DateTime.civil event["time(1i)"].to_i, event["time(2i)"].to_i, event["time(3i)"].to_i, event["time(4i)"].to_i, event["time(5i)"].to_i
  	i = Interview.new
  	i.time = interview_time
  	i.location = event[:location]
  	i.save
  	redirect_to :back
  end

  def signup
    interview = Interview.find(params[:id])
    if current_user.is_admin? or current_user.is_reviewer?
      interview.interviewer_id = current_user.id
    elsif current_user.is_applicant?
      interview.applicant_id = current_user.id
    end
    interview.save()
    redirect_to :back
  end

  def cancel
    interview = Interview.find(params[:id])
    if current_user.is_admin? or current_user.is_reviewer?
      interview.interviewer_id = nil
    elsif current_user.is_applicant?
      interview.applicant_id = nil
    end
    interview.save()
    redirect_to :back
  end

  def admin
    @interviews = Interview.all
    @new_interview = Interview.new
  end

  private
    def interview_update_params
      params.require(:interview).permit(:rating, :comment)
    end
  	def interview_params
  		params.require(:interview)
  	end
end

app/helpers/interview_helper.rb
module InterviewHelper
end

app/views/interview/admin.html.erb
<% if not @interviews.blank? %>
<h2>All Interviews</h2>
<table>
	<tr>
		<td>id</td>
		<td>Applicant Name</td>
		<td>Interviewer Name</td>
		<td>Datetime</td>
		<td>Location</td>
		<td>Rating & Comment</td>
	</tr>
	<% @interviews.each do |i| %>
	<tr>
		<td><%= link_to i.id, interview_path(i) %></td>
		<td><%= i.applicant_name %></td>
		<td><%= i.interviewer_name %></td>
		<td><%= i.time %></td>
		<td><%= i.location %></td>
		<td>
		<%= form_for i, url: {action: "update", controller: "interview", id: i.id} do |f| %>
			<%= f.text_area :comment %>
			<%= select_tag("interview[rating]", options_for_select(["1", "2", "3"],  i.rating)) %>
			<%= f.submit %>
		<% end %>
		</td>
	</tr>
	<% end %>
</table>
<% else %>
<p>There are no interviews available.</p>
<% end %>
<h3>Create New Interview Timeslot</h3>
<%= form_for @new_interview, url: {action: :create} do |f| %>
	<%= f.text_field :location, placeholder: "location" %>
	<%= f.datetime_select :time, ampm: true, minute_step: 15 %>
	<%= f.submit %>
<% end %>

app/views/interview/index.html.erb
<% if not @my_interviews.blank? %>
<h2>Your Interviews</h2>
<table>
	<tr>
		<td>id</td>
		<td>Applicant Name</td>
		<td>Interviewer Name</td>
		<td>Datetime</td>
		<td>Location</td>
		<td>Rating & Comment</td>
		<td>Cancel</td>
	</tr>
	<% @my_interviews.each do |i| %>
	<tr>
		<td><%= link_to i.id, interview_path(i) %></td>
		<td><%= i.applicant_name %></td>
		<td><%= i.interviewer_name %></td>
		<td><%= i.time %></td>
		<td><%= i.location %></td>
		<td>
		<%= form_for i, url: {action: "update", controller: "interview", id: i.id} do |f| %>
			<%= f.text_area :comment %>
			<%= select_tag("interview[rating]", options_for_select(["1", "2", "3"],  i.rating)) %>
			<%= f.submit %>
		<% end %>
		</td>
		<td><%= link_to "Cancel", interview_cancel_path(i.id) %></td>
	</tr>
	<% end %>
</table>
<% else %>
<p>You don't have any interviews scheduled.</p>
<% end %>
<% if not @interviews.blank? %>
<h2>All Interviews</h2>
<table>
	<tr>
		<td>id</td>
		<td>Applicant Name</td>
		<td>Interviewer Name</td>
		<td>Datetime</td>
		<td>Location</td>
		<td>Sign Up</td>
	</tr>
	<% @interviews.each do |i| %>
	<tr>
		<td><%= link_to i.id, interview_path(i) %></td>
		<td><%= i.applicant_name %></td>
		<td><%= i.interviewer_name %></td>
		<td><%= i.time %></td>
		<td><%= i.location %></td>
		<td><%= link_to "Sign Up", interview_signup_path(i.id) %></td>
	</tr>
	<% end %>
</table>
<% else %>
<p>There are no interviews available.</p>
<% end %>

app/views/interview/show.html.erb
<h1>Interview#show</h1>
<p>Find me in app/views/interview/show.html.erb</p>

app/views/interview/update.html.erb
<h1>Interview#update</h1>
<p>Find me in app/views/interview/update.html.erb</p>